# Generated by Django 3.2.9 on 2022-05-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_id', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=200)),
                ('Ph_no', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'DETAILS',
            },
        ),
        migrations.CreateModel(
            name='LOGIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'LOGIN',
            },
        ),
    ]
