# Generated by Django 3.2.9 on 2022-05-06 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='D_id',
        ),
    ]
